version: '3.5'
services:

  nginx:
    image: chusj/clin-external-reverse-proxy:1
    volumes:
      #     - ./data/certbot/conf:/etc/letsencrypt  --for local usage
      #      - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
      - "sshvolume:/etc/letsencrypt"
    ports:
      - 443:443
      - 10000:10000
      - 10001:10001
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.node_role == devops]
    networks:
      - proxy
    command: bin/bash -c "nginx -g 'daemon off;'"

networks:
  proxy:
    external: true

volumes:
  sshvolume:
    external: true